name: Validate packer AMI
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Validate packer AMI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Setup packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Compress codebase
        id: tarFile
        run: touch webapp.tar.gz

      - name: Run `packer init`
        id: init
        run: "packer init scripts/aws-ami.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate scripts/aws-ami.pkr.hcl"
